In [3]:
with open('pg11310.txt', 'r', encoding='utf-8') as f:
    text = f.read()

print(len(text))
print(text[:200])

chars = sorted(set(text))
print(chars)

print(len(chars))

225568
Hindu Tales from the Sanskrit


Translated by
S. M. Mitra

Adapted by
Mrs. Arthur Bell

1919


Contents

 INTRODUCTORY NOTE

 1. The Magic Pitcher
 2. The Story of a Cat, a Mouse, a Lizard and an Owl

['\n', ' ', '!', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '—', '‘', '’', '“', '”']
78


In [4]:
string_to_int = {ch:i for i, ch in enumerate(chars)}
int_to_string = {i:ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

print(decode(encode('hello')))

hello


In [5]:
import torch
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
device = 'mps' if torch.backends.mps.is_available() else 'cpu'

print(device)

mps


In [6]:
data = torch.tensor(encode(text), dtype=torch.long)

In [7]:
print(data[:100])

tensor([27, 55, 60, 50, 67,  1, 38, 47, 58, 51, 65,  1, 52, 64, 61, 59,  1, 66,
        54, 51,  1, 37, 47, 60, 65, 57, 64, 55, 66,  0,  0,  0, 38, 64, 47, 60,
        65, 58, 47, 66, 51, 50,  1, 48, 71,  0, 37,  6,  1, 32,  6,  1, 32, 55,
        66, 64, 47,  0,  0, 20, 50, 47, 62, 66, 51, 50,  1, 48, 71,  0, 32, 64,
        65,  6,  1, 20, 64, 66, 54, 67, 64,  1, 21, 51, 58, 58,  0,  0,  8, 16,
         8, 16,  0,  0,  0, 22, 61, 60, 66, 51])


In [8]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

In [9]:
print(n)
print('------')
print(train_data)
print('------')
print(val_data)

180454
------
tensor([27, 55, 60,  ..., 66, 54, 61])
------
tensor([67, 53, 54,  ...,  0,  0,  0])


In [10]:
block_size = 8
x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print('when input is', context, 'target is', target)

when input is tensor([27]) target is tensor(55)
when input is tensor([27, 55]) target is tensor(60)
when input is tensor([27, 55, 60]) target is tensor(50)
when input is tensor([27, 55, 60, 50]) target is tensor(67)
when input is tensor([27, 55, 60, 50, 67]) target is tensor(1)
when input is tensor([27, 55, 60, 50, 67,  1]) target is tensor(38)
when input is tensor([27, 55, 60, 50, 67,  1, 38]) target is tensor(47)
when input is tensor([27, 55, 60, 50, 67,  1, 38, 47]) target is tensor(58)
